export function generateData() {
  return [
    // L1 tools (y = 0-1)
    {
      name: 'GitHub Copilot',
      level: 'L1',
      domain: 'general',
      x: 1.45,
      y: 0.23,
      status: 'available',
    },
    {
      name: 'Codium',
      level: 'L1',
      domain: 'general',
      x: 1.3,
      y: 0.8,
      status: 'available',
    },
    {
      name: 'Codeium',
      level: 'L1',
      domain: 'general',
      x: 1.74,
      y: 0.7,
      status: 'available',
    },
    {
      name: 'Tabby',
      level: 'L1',
      domain: 'general',
      x: 1.4,
      y: 0.5,
      status: 'available',
    },

    // L2 tools (y = 1-2)
    // {
    //   name: 'ChatGPT',
    //   level: 'L2',
    //   domain: 'general',
    //   x: 1.7,
    //   y: 1.1,
    //   status: 'foundation',
    // },
    // {
    //   name: 'Claude',
    //   level: 'L2',
    //   domain: 'general',
    //   x: 1.3,
    //   y: 1.1,
    //   status: 'foundation',
    // },
    {
      name: 'Amazon Q Developer',
      level: 'L2',
      domain: 'general',
      x: 1.04,
      y: 1.2,
      status: 'available',
    },
    {
      name: 'aider',
      level: 'L2',
      domain: 'general',
      x: 1.61,
      y: 1.2,
      status: 'available',
    },
    {
      name: 'cline',
      level: 'L2',
      domain: 'general',
      x: 1.82,
      y: 1.2,
      status: 'available',
    },
    {
      name: 'Roo Code',
      level: 'L2',
      domain: 'general',
      x: 1.74,
      y: 1.4,
      status: 'available',
    },
    {
      name: 'Repo Prompt',
      level: 'L2',
      domain: 'general',
      x: 1.1,
      y: 1.4,
      status: 'available',
    },

    {
      name: '16x Prompt',
      level: 'L2',
      domain: 'general',
      x: 1.43,
      y: 1.4,
      status: 'available',
    },

    {
      name: 'Continue',
      level: 'L2',
      domain: 'general',
      x: 1.42,
      y: 1.6,
      status: 'available',
    },
    {
      name: 'PearAI',
      level: 'L2',
      domain: 'general',
      x: 1.18,
      y: 1.6,
      status: 'available',
    },
    {
      name: 'Windsurf',
      level: 'L2',
      domain: 'general',
      x: 1.4,
      y: 1.8,
      status: 'available',
    },
    {
      name: 'Trae',
      level: 'L2',
      domain: 'general',
      x: 1.1,
      y: 1.8,
      status: 'available',
    },
    {
      name: 'Cursor',
      level: 'L2',
      domain: 'general',
      x: 1.72,
      y: 1.8,
      status: 'available',
      popular: true,
    },

    // L3 tools (y = 2-3)
    // Webdev
    {
      name: 'Replit CDE',
      level: 'L3',
      domain: 'webdev',
      x: 0.6,
      y: 2.32,
      status: 'available',
    },
    {
      name: 'v0',
      level: 'L3',
      domain: 'webdev',
      x: 0.4,
      y: 2.8,
      status: 'available',
    },
    {
      name: 'CerebrasCoder',
      level: 'L3',
      domain: 'webdev',
      x: 0.2,
      y: 2.48,
      status: 'available',
    },
    {
      name: 'Tempo',
      level: 'L3',
      domain: 'webdev',
      x: 0.8,
      y: 2.5,
      status: 'available',
    },
    // General
    {
      name: 'Codegen',
      level: 'L3',
      domain: 'general',
      x: 1.7,
      y: 2.2,
      status: 'available',
    },
    {
      name: 'GitHub Copilot (Agent)',
      level: 'L3',
      domain: 'general',
      x: 1.06,
      y: 2.2,
      status: 'available',
    },
    {
      name: 'Pythagora',
      level: 'L3',
      domain: 'general',
      x: 1.6,
      y: 2.4,
      status: 'waitlist',
    },
    {
      name: 'Sweep',
      level: 'L3',
      domain: 'general',
      x: 1.22,
      y: 2.4,
      status: 'beta',
    },
    {
      name: 'Claude Code',
      level: 'L3',
      domain: 'general',
      x: 1.15,
      y: 2.6,
      status: 'available',
      popular: true,
    },
    {
      name: 'OpenAI Codex',
      level: 'L3',
      domain: 'general',
      x: 1.65,
      y: 2.6,
      status: 'available',
    },
    {
      name: 'Google Jules',
      level: 'L3',
      domain: 'general',
      x: 1.45,
      y: 2.8,
      status: 'available',
    },
    // L4 tools (y = 3-4)
    {
      name: 'Devin',
      level: 'L4',
      domain: 'general',
      x: 1.7,
      y: 3.32,
      status: 'available',
    },
    {
      name: 'devlo',
      level: 'L4',
      domain: 'general',
      x: 1.1,
      y: 3.32,
      status: 'available',
    },
    {
      name: 'Genie',
      level: 'L4',
      domain: 'general',
      x: 1.3,
      y: 3.8,
      status: 'waitlist',
    },
    {
      name: 'Engine',
      level: 'L4',
      domain: 'general',
      x: 1.64,
      y: 3.6,
      status: 'beta',
    },
    {
      name: 'Marblism',
      level: 'L4',
      domain: 'webdev',
      x: 0.65,
      y: 3.3,
      status: 'available',
    },
    {
      name: 'bolt.new',
      level: 'L4',
      domain: 'webdev',
      x: 0.3,
      y: 3.64,
      status: 'available',
    },
    {
      name: 'Trickle',
      level: 'L4',
      domain: 'webdev',
      x: 0.72,
      y: 3.5,
      status: 'available',
    },
    {
      name: 'Lovable',
      level: 'L4',
      domain: 'webdev',
      x: 0.2,
      y: 3.87,
      status: 'available',
      popular: true,
    },
    {
      name: 'Replit Agent',
      level: 'L4',
      domain: 'webdev',
      x: 0.5,
      y: 3.87,
      status: 'available',
    },

    // L5 tools (y = 4-5)
    {
      name: 'AutoDev',
      level: 'L5',
      domain: 'general',
      x: 1.67,
      y: 4.4,
      status: 'waitlist',
    },
    {
      name: 'MetaGPT',
      level: 'L5',
      domain: 'general',
      x: 1.21,
      y: 4.8,
      status: 'waitlist',
    },
    {
      name: 'MGX',
      level: 'L5',
      domain: 'general',
      x: 1.77,
      y: 4.6,
      status: 'waitlist',
    },
    {
      name: 'MultiDevin',
      level: 'L5',
      domain: 'general',
      x: 1.27,
      y: 4.54,
      status: 'beta',
    },
  ];
}
