export function generateData() {
  return [
    // L1 tools (y = 0-1)
    {
      name: 'GitHub Copilot',
      level: 'L1',
      domain: 'general',
      x: 2.4,
      y: 0.3,
      status: 'available',
    },
    {
      name: 'Codium',
      level: 'L1',
      domain: 'general',
      x: 2.1,
      y: 0.8,
      status: 'available',
    },
    {
      name: 'Codeium',
      level: 'L1',
      domain: 'general',
      x: 2.7,
      y: 0.7,
      status: 'available',
    },
    {
      name: 'Tabby',
      level: 'L1',
      domain: 'general',
      x: 2.15,
      y: 0.5,
      status: 'available',
    },

    // L2 tools (y = 1-2)
    {
      name: 'ChatGPT',
      level: 'L2',
      domain: 'general',
      x: 2.6,
      y: 1.1,
      status: 'foundation',
    },
    {
      name: 'Claude',
      level: 'L2',
      domain: 'general',
      x: 2.2,
      y: 1.1,
      status: 'foundation',
    },
    {
      name: 'aider',
      level: 'L2',
      domain: 'general',
      x: 2.18,
      y: 1.32,
      status: 'available',
    },
    {
      name: 'cline',
      level: 'L2',
      domain: 'general',
      x: 2.63,
      y: 1.32,
      status: 'available',
    },
    {
      name: 'Continue',
      level: 'L2',
      domain: 'general',
      x: 2.54,
      y: 1.5,
      status: 'available',
    },
    {
      name: 'Repo Prompt',
      level: 'L2',
      domain: 'general',
      x: 2.07,
      y: 1.52,
      status: 'available',
    },
    {
      name: 'Cursor',
      level: 'L2',
      domain: 'general',
      x: 2.6,
      y: 1.71,
      status: 'available',
    },
    {
      name: 'PearAI',
      level: 'L2',
      domain: 'general',
      x: 2.15,
      y: 1.69,
      status: 'available',
    },
    {
      name: 'Windsurf',
      level: 'L2',
      domain: 'general',
      x: 2.32,
      y: 1.86,
      status: 'available',
    },

    // L3 tools (y = 2-3)
    {
      name: 'Replit CDE',
      level: 'L3',
      domain: 'fullstack',
      x: 1.3,
      y: 2.4,
      status: 'available',
    },
    {
      name: 'Codegen',
      level: 'L3',
      domain: 'general',
      x: 2.6,
      y: 2.4,
      status: 'available',
    },
    {
      name: 'Sweep',
      level: 'L3',
      domain: 'general',
      x: 2.2,
      y: 2.8,
      status: 'beta',
    },
    {
      name: 'Pythagora',
      level: 'L3',
      domain: 'general',
      x: 2.5,
      y: 2.6,
      status: 'waitlist',
    },
    {
      name: 'v0',
      level: 'L3',
      domain: 'frontend',
      x: 0.2,
      y: 2.3,
      status: 'available',
    },
    {
      name: 'CerebrasCoder',
      level: 'L3',
      domain: 'frontend',
      x: 0.3,
      y: 2.7,
      status: 'available',
    },
    {
      name: 'Tempo',
      level: 'L3',
      domain: 'frontend',
      x: 0.74,
      y: 2.5,
      status: 'available',
    },

    // L4 tools (y = 3-4)
    {
      name: 'Devin',
      level: 'L4',
      domain: 'general',
      x: 2.6,
      y: 3.4,
      status: 'available',
    },
    {
      name: 'Genie',
      level: 'L4',
      domain: 'general',
      x: 2.2,
      y: 3.8,
      status: 'waitlist',
    },
    {
      name: 'Engine',
      level: 'L4',
      domain: 'general',
      x: 2.72,
      y: 3.6,
      status: 'beta',
    },
    {
      name: 'Marblism',
      level: 'L4',
      domain: 'fullstack',
      x: 1.5,
      y: 3.3,
      status: 'available',
    },
    {
      name: 'bolt.new',
      level: 'L4',
      domain: 'fullstack',
      x: 1.2,
      y: 3.7,
      status: 'available',
    },
    {
      name: 'Trickle',
      level: 'L4',
      domain: 'fullstack',
      x: 1.7,
      y: 3.5,
      status: 'available',
    },
    {
      name: 'Lovable',
      level: 'L4',
      domain: 'fullstack',
      x: 1.12,
      y: 3.9,
      status: 'available',
    },
    {
      name: 'Replit Agent',
      level: 'L4',
      domain: 'fullstack',
      x: 1.54,
      y: 3.87,
      status: 'available',
    },

    // L5 tools (y = 4-5)
    {
      name: 'AutoDev',
      level: 'L5',
      domain: 'general',
      x: 2.6,
      y: 4.4,
      status: 'waitlist',
    },
    {
      name: 'MetaGPT',
      level: 'L5',
      domain: 'general',
      x: 2.2,
      y: 4.8,
      status: 'waitlist',
    },
    {
      name: 'MGX',
      level: 'L5',
      domain: 'general',
      x: 2.8,
      y: 4.6,
      status: 'waitlist',
    },
  ];
}
